source 'https://rubygems.org'
#For testing
gem 'rspec','3.1.0'
gem 'rspec-retry'
gem 'poltergeist'
gem 'capybara'
gem 'capybara-screenshot', :group => :test
gem 'capybara-screenshot-s3', group: :test, require: false